CREATE TABLE money_market_order (
    id                           UUID            NOT NULL,
    external_order_reference     VARCHAR(100)    NOT NULL,
    order_type                   VARCHAR(20)     NOT NULL,
    order_operation              VARCHAR(20)     NOT NULL,
    portfolio_number             VARCHAR(50)     NOT NULL,
    currency                     VARCHAR(3)      NOT NULL,
    amount                       DECIMAL(18, 2)  NOT NULL,
    value_date                   DATE            NOT NULL,
    minimum_rate                 DECIMAL(12, 8)  NOT NULL,
    tenor                        VARCHAR(10)     NULL,
    notice_period                VARCHAR(10)     NULL,
    source_contract_number       VARCHAR(50)     NULL,
    desired_counterparty_comment TEXT            NULL,
    status                       VARCHAR(20)     NOT NULL,
    assigned_trader_id           VARCHAR(100)    NULL,
    assigned_at                  TIMESTAMP WITH TIME ZONE NULL,
    executed_rate                DECIMAL(12, 8)  NULL,
    counterparty                 VARCHAR(200)    NULL,
    execution_time               TIMESTAMP WITH TIME ZONE NULL,
    dealing_reference            VARCHAR(50)     NULL,
    generated_contract_number    VARCHAR(50)     NULL,
    rejection_reason             TEXT            NULL,
    created_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_money_market_order PRIMARY KEY (id)
);
