export enum OrderStatus {
  RECEIVED = 'RECEIVED',
  ROUTED = 'ROUTED',
  ASSIGNED = 'ASSIGNED',
  EXECUTED = 'EXECUTED',
  ACCOUNTED = 'ACCOUNTED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}
