package com.mmx.order.contract;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.yaml.snakeyaml.Yaml;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Task 7.2: Lightweight unit checks that OpenAPI and AsyncAPI contract specimens stay in sync
 * with golden fixtures and codegen output. No Spring context, no Testcontainers.
 *
 * <ul>
 *   <li>AsyncAPI ↔ canonical JSON Schema: required fields and property keys must match.</li>
 *   <li>OpenAPI codegen: generated {@code OrderSummaryResponse} must expose {@code handoffStatus}
 *       and the generated {@code HandoffStatus} enum must declare all three contract values.</li>
 * </ul>
 */
class ContractSyncVerificationTest {

    private static final String CANONICAL_SCHEMA_CLASSPATH = "/contracts/OrderExecutedV1.json";
    private static final String CANONICAL_SCHEMA_RELATIVE =
            "../../contracts/002-trader-orders-views/schemas/OrderExecutedV1.json";
    private static final String ASYNCAPI_CONTRACT_RELATIVE =
            "../../contracts/002-trader-orders-views/asyncapi.yaml";

    private static final ObjectMapper JSON = new ObjectMapper();

    @Test
    void asyncApiOrderExecutedV1_payloadRef_pointsAtCanonicalSchemaFile() throws Exception {
        Map<String, Object> asyncApiDoc = loadAsyncApiYaml();

        @SuppressWarnings("unchecked")
        Map<String, Object> messages = (Map<String, Object>)
                ((Map<String, Object>) asyncApiDoc.get("components")).get("messages");
        @SuppressWarnings("unchecked")
        Map<String, Object> orderExecutedV1 = (Map<String, Object>) messages.get("OrderExecutedV1");
        @SuppressWarnings("unchecked")
        Map<String, Object> payload = (Map<String, Object>) orderExecutedV1.get("payload");

        assertThat(payload.get("$ref"))
                .as("AsyncAPI OrderExecutedV1 payload must reference external canonical schema")
                .isEqualTo("./schemas/OrderExecutedV1.json");
    }

    @Test
    void asyncApiOrderExecutedV1_classpathSchemaRequired_matchesCanonicalFile() throws Exception {
        JsonNode classpathSchema = loadClasspathSchema();
        JsonNode fileSchema = loadCanonicalSchemaFile();

        Set<String> classpathRequired = new HashSet<>();
        classpathSchema.path("required").forEach(n -> classpathRequired.add(n.asText()));

        Set<String> fileRequired = new HashSet<>();
        fileSchema.path("required").forEach(n -> fileRequired.add(n.asText()));

        assertThat(classpathRequired)
                .as("classpath schema 'required' must match canonical OrderExecutedV1.json on disk")
                .containsExactlyInAnyOrderElementsOf(fileRequired);
    }

    @Test
    void asyncApiOrderExecutedV1_classpathSchemaProperties_matchesCanonicalFile() throws Exception {
        JsonNode classpathSchema = loadClasspathSchema();
        JsonNode fileSchema = loadCanonicalSchemaFile();

        Set<String> classpathProperties = new HashSet<>();
        classpathSchema.path("properties").fieldNames().forEachRemaining(classpathProperties::add);

        Set<String> fileProperties = new HashSet<>();
        fileSchema.path("properties").fieldNames().forEachRemaining(fileProperties::add);

        assertThat(classpathProperties)
                .as("classpath schema 'properties' keys must match canonical OrderExecutedV1.json on disk")
                .containsExactlyInAnyOrderElementsOf(fileProperties);
    }

    @Test
    void openApiCodegen_orderSummaryResponse_exposesHandoffStatusGetter() throws Exception {
        Class<?> responseClass = Class.forName(
                "com.mmx.order.adapter.in.rest.generated.model.OrderSummaryResponse");
        java.lang.reflect.Method getter = responseClass.getMethod("getHandoffStatus");
        assertThat(getter)
                .as("OrderSummaryResponse generated by OpenAPI codegen must have getHandoffStatus()")
                .isNotNull();
    }

    @Test
    void openApiCodegen_handoffStatus_declaresExactContractEnumValues() throws Exception {
        Class<?> handoffStatusClass = Class.forName(
                "com.mmx.order.adapter.in.rest.generated.model.HandoffStatus");
        assertThat(handoffStatusClass.isEnum())
                .as("HandoffStatus generated by OpenAPI codegen must be an enum")
                .isTrue();

        Set<String> enumConstants = new HashSet<>();
        for (Object constant : handoffStatusClass.getEnumConstants()) {
            enumConstants.add(((Enum<?>) constant).name());
        }
        assertThat(enumConstants)
                .as("HandoffStatus enum must declare exactly PENDING, PUBLISHED, FAILED per OpenAPI contract")
                .containsExactlyInAnyOrder("PENDING", "PUBLISHED", "FAILED");
    }

    private JsonNode loadClasspathSchema() throws Exception {
        try (InputStream in = getClass().getResourceAsStream(CANONICAL_SCHEMA_CLASSPATH)) {
            Objects.requireNonNull(in, "Missing classpath schema " + CANONICAL_SCHEMA_CLASSPATH);
            return JSON.readTree(in);
        }
    }

    private JsonNode loadCanonicalSchemaFile() throws Exception {
        Path schemaPath = resolveCanonicalSchemaPath();
        return JSON.readTree(Files.readString(schemaPath));
    }

    private Map<String, Object> loadAsyncApiYaml() throws Exception {
        Path contractPath = resolveAsyncApiPath();
        try (InputStream in = Files.newInputStream(contractPath)) {
            return new Yaml().load(in);
        }
    }

    private Path resolveCanonicalSchemaPath() {
        Path candidate = Paths.get(CANONICAL_SCHEMA_RELATIVE).toAbsolutePath().normalize();
        if (Files.exists(candidate)) {
            return candidate;
        }
        Path dir = Paths.get("").toAbsolutePath();
        while (dir != null) {
            Path target =
                    dir.resolve("contracts/002-trader-orders-views/schemas/OrderExecutedV1.json");
            if (Files.exists(target)) {
                return target;
            }
            dir = dir.getParent();
        }
        throw new IllegalStateException(
                "Cannot locate canonical schema. Searched: " + candidate);
    }

    private Path resolveAsyncApiPath() {
        Path candidate = Paths.get(ASYNCAPI_CONTRACT_RELATIVE).toAbsolutePath().normalize();
        if (Files.exists(candidate)) {
            return candidate;
        }
        Path dir = Paths.get("").toAbsolutePath();
        while (dir != null) {
            Path target = dir.resolve("contracts/002-trader-orders-views/asyncapi.yaml");
            if (Files.exists(target)) {
                return target;
            }
            dir = dir.getParent();
        }
        throw new IllegalStateException(
                "Cannot locate contracts/002-trader-orders-views/asyncapi.yaml. "
                        + "Searched relative path: " + candidate);
    }
}
