package com.mmx.order.contract;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.yaml.snakeyaml.Yaml;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Task 7.2: Lightweight unit checks that OpenAPI and AsyncAPI contract specimens stay in sync
 * with golden fixtures and codegen output. No Spring context, no Testcontainers.
 *
 * <ul>
 *   <li>AsyncAPI ↔ JSON Schema golden fixture: required fields and property keys must match.</li>
 *   <li>OpenAPI codegen: generated {@code OrderSummaryResponse} must expose {@code handoffStatus}
 *       and the generated {@code HandoffStatus} enum must declare all three contract values.</li>
 * </ul>
 */
class ContractSyncVerificationTest {

    private static final String ASYNC_SCHEMA_FIXTURE = "/contracts/order-executed-v1-payload.schema.json";
    private static final String ASYNCAPI_CONTRACT_RELATIVE =
            "../../specs/002-trader-orders-views/contracts/asyncapi.yaml";

    private static final ObjectMapper JSON = new ObjectMapper();

    @Test
    void asyncApiOrderExecutedV1_goldenFixtureRequired_matchesAsyncApiSchema() throws Exception {
        Map<String, Object> asyncApiDoc = loadAsyncApiYaml();

        @SuppressWarnings("unchecked")
        Map<String, Object> schemas = (Map<String, Object>)
                ((Map<String, Object>) asyncApiDoc.get("components")).get("schemas");
        @SuppressWarnings("unchecked")
        Map<String, Object> asyncApiSchema = (Map<String, Object>) schemas.get("OrderExecutedV1");
        @SuppressWarnings("unchecked")
        List<String> asyncApiRequired = (List<String>) asyncApiSchema.get("required");

        Set<String> goldenRequired = new HashSet<>();
        loadGoldenFixture().path("required").forEach(n -> goldenRequired.add(n.asText()));

        assertThat(goldenRequired)
                .as("golden fixture 'required' fields must match AsyncAPI OrderExecutedV1 schema")
                .containsExactlyInAnyOrderElementsOf(asyncApiRequired);
    }

    @Test
    void asyncApiOrderExecutedV1_goldenFixtureProperties_matchesAsyncApiSchema() throws Exception {
        Map<String, Object> asyncApiDoc = loadAsyncApiYaml();

        @SuppressWarnings("unchecked")
        Map<String, Object> schemas = (Map<String, Object>)
                ((Map<String, Object>) asyncApiDoc.get("components")).get("schemas");
        @SuppressWarnings("unchecked")
        Map<String, Object> asyncApiSchema = (Map<String, Object>) schemas.get("OrderExecutedV1");
        @SuppressWarnings("unchecked")
        Map<String, Object> asyncApiProperties = (Map<String, Object>) asyncApiSchema.get("properties");

        Set<String> goldenProperties = new HashSet<>();
        loadGoldenFixture().path("properties").fieldNames().forEachRemaining(goldenProperties::add);

        assertThat(goldenProperties)
                .as("golden fixture 'properties' keys must match AsyncAPI OrderExecutedV1 schema")
                .containsExactlyInAnyOrderElementsOf(asyncApiProperties.keySet());
    }

    @Test
    void openApiCodegen_orderSummaryResponse_exposesHandoffStatusGetter() throws Exception {
        Class<?> responseClass = Class.forName(
                "com.mmx.order.adapter.in.rest.generated.model.OrderSummaryResponse");
        java.lang.reflect.Method getter = responseClass.getMethod("getHandoffStatus");
        assertThat(getter)
                .as("OrderSummaryResponse generated by OpenAPI codegen must have getHandoffStatus()")
                .isNotNull();
    }

    @Test
    void openApiCodegen_handoffStatus_declaresExactContractEnumValues() throws Exception {
        Class<?> handoffStatusClass = Class.forName(
                "com.mmx.order.adapter.in.rest.generated.model.HandoffStatus");
        assertThat(handoffStatusClass.isEnum())
                .as("HandoffStatus generated by OpenAPI codegen must be an enum")
                .isTrue();

        Set<String> enumConstants = new HashSet<>();
        for (Object constant : handoffStatusClass.getEnumConstants()) {
            enumConstants.add(((Enum<?>) constant).name());
        }
        assertThat(enumConstants)
                .as("HandoffStatus enum must declare exactly PENDING, PUBLISHED, FAILED per OpenAPI contract")
                .containsExactlyInAnyOrder("PENDING", "PUBLISHED", "FAILED");
    }

    // --- helpers ---

    private JsonNode loadGoldenFixture() throws Exception {
        try (InputStream in = getClass().getResourceAsStream(ASYNC_SCHEMA_FIXTURE)) {
            Objects.requireNonNull(in, "Missing contract fixture " + ASYNC_SCHEMA_FIXTURE);
            return JSON.readTree(in);
        }
    }

    private Map<String, Object> loadAsyncApiYaml() throws Exception {
        Path contractPath = resolveAsyncApiPath();
        try (InputStream in = Files.newInputStream(contractPath)) {
            return new Yaml().load(in);
        }
    }

    private Path resolveAsyncApiPath() {
        // Maven executes tests with CWD = module dir (mmx-bootstrap); navigate up to project root.
        Path candidate = Paths.get(ASYNCAPI_CONTRACT_RELATIVE).toAbsolutePath().normalize();
        if (Files.exists(candidate)) {
            return candidate;
        }
        // Fallback: walk up from CWD looking for the specs directory.
        Path dir = Paths.get("").toAbsolutePath();
        while (dir != null) {
            Path target = dir.resolve("specs/002-trader-orders-views/contracts/asyncapi.yaml");
            if (Files.exists(target)) {
                return target;
            }
            dir = dir.getParent();
        }
        throw new IllegalStateException(
                "Cannot locate specs/002-trader-orders-views/contracts/asyncapi.yaml. "
                        + "Searched relative path: " + candidate);
    }
}
