CREATE TABLE managed_currency (
    code CHAR(3) NOT NULL PRIMARY KEY,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    min_subscription_amount DECIMAL(18, 2) NOT NULL,
    min_increase_decrease_amount DECIMAL(18, 2) NOT NULL,
    tenor_1w BOOLEAN NOT NULL DEFAULT FALSE,
    tenor_2w BOOLEAN NOT NULL DEFAULT FALSE,
    tenor_1m BOOLEAN NOT NULL DEFAULT FALSE,
    tenor_3m BOOLEAN NOT NULL DEFAULT FALSE,
    tenor_6m BOOLEAN NOT NULL DEFAULT FALSE,
    tenor_1y BOOLEAN NOT NULL DEFAULT FALSE,
    notice_24h BOOLEAN NOT NULL DEFAULT FALSE,
    notice_48h BOOLEAN NOT NULL DEFAULT FALSE
);
